- name: |
    "5.1 Configure time-based job schedulers"
    "5.1.1 Ensure cron daemon is enabled and running (Automated)"
  become: yes
  systemd:
    name: cron
    state: started
    enabled: yes
  when: level1|bool
  tags:
    - section5
    - section5.1
    - section5.1.1

- name: "5.1.2 Ensure permissions on /etc/crontab are configured (Automated)"
  become: yes
  file:
    path: "/etc/crontab"
    owner: root
    group: root
    mode: 0600
  when: level1|bool
  tags:
    - section5
    - section5.1
    - section5.1.2
    
- name: |
    "5.1.3 Ensure permissions on /etc/cron.hourly are configured (Automated)"
    "5.1.4 Ensure permissions on /etc/cron.daily are configured (Automated)"
    "5.1.5 Ensure permissions on /etc/cron.weekly are configured (Automated)"
    "5.1.6 Ensure permissions on /etc/cron.monthly are configured (Automated)"
    "5.1.7 Ensure permissions on /etc/cron.d are configured (Automated)"
  become: yes
  file: 
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0700
  with_items:
    - /etc/cron.hourly/
    - /etc/cron.daily/
    - /etc/cron.monthly/
    - /etc/cron.weekly/
    - /etc/cron.d/
  when: level1|bool
  tags:
    - section5
    - section5.1
    - section5.1.3
    - section5.1.4
    - section5.1.5
    - section5.1.6

- name: "5.1.8 Ensure cron is restricted to authorized users (Automated)"
  become: yes
  block:
    - file:
        path: "/etc/cron.deny"
        state: absent
    - file:
        path: "/etc/cron.allow"
        state: touch
        owner: root
        group: root
        mode: 0640
  when: level1|bool
  tags:
    - section5
    - section5.1
    - section5.1.8

- name: "5.1.9 Ensure at is restricted to authorized users (Automated)"
  become: yes
  block:
    - file:
        path: "/etc/at.deny"
        state: absent
    - file:
        path: "/etc/at.allow"
        state: touch
        owner: root
        group: root
        mode: 0640
  when: level1|bool
  tags:
    - section5
    - section5.1
    - section5.1.9

