- name: "5.3.1 Ensure sudo is installed (Automated)"
  become: ye
  block:
    - apt:
        name: sudo
        state: present
    - lineinfile:
      path: "/etc/sudoers"
      regexp: "(?i)%sudo"
      state: absent
      owner: root
      group: root
      mode: 0640
  when: level1|bool
  tags:
    - section5
    - section5.3
    - section5.3.1
  
- name: "5.3.2 Ensure sudo commands use pty (Automated)"
  become: yes
  lineinfile:
    path: "/etc/sudoers"
    regexp: "(?i)Defaults use_pty"
    line: "Defaults use_pty"
  when: level1|bool
  tags:
    - section5
    - section5.3
    - section5.3.2

- name: "5.3.3 Ensure sudo log file exists (Automated)"
  become: yes
  lineinfile:
    path: "/etc/sudoers"
    regexp: "(?i)Defaults logfile"
    line: "Defaults logfile="/var/log/sudo.log""
  when: level1|bool
  tags:
    - section5
    - section5.3
    - section5.3.3  

- name: "5.3.4 Ensure users must provide password for privilege escalation (Automated)"
  become: yes
  lineinfile:
    path: "/etc/sudoers"
    regexp: "(?i)Defaults logfile"
    line: 'Defaults logfile="/var/log/sudo.log"'
  when: level2|bool
  tags:
    - section5
    - section5.3
    - section5.3.4

- name: "5.3.5 Ensure re-authentication for privilege escalation is not disabled globally (Automated)"

- name: "5.3.6 Ensure sudo authentication timeout is configured correctly (Automated)"
  become: yes
  block:
    - lineinfile:
        path: "/etc/sudoers"
        regexp: "(?i)Defaults env_reset"
        line: "Defaults env_reset"
    - lineinfile:
        path: "/etc/sudoers"
        regexp: "(?i)Defaults timestamp_timeout"
        line: "Defaults timestamp_timeout=15"
  when: level1|bool
  tags:
    - section5
    - section5.3
    - section5.3.6 

- name: "5.3.7 Ensure access to the su command is restricted (Automated)"
  become: yes
  block:
    - group:
        name: suusers
        state: present
    - user:
        name: povadmin
        group: suusers
    - lineinfile:
        path: "/etc/pam.d/su"
        regexp: "(?i)auth required pam_wheel.so use_uid group=suusers"
        line: "auth required pam_wheel.so use_uid group=suusers"
  when: level1|bool
  tags:
    - section5
    - section5.3
    - section5.3.7

