- name: "3.2.1 Ensure packet redirect sending is disabled (Automated)"
  become: yes
  sysctl:
    name: "{{ item }}"
    value: '0'
    state: present
    reload: true
    sysctl_set: true
    ignoreerrors: true
  with_items:
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects
  when: level1|bool
  tags:
    - section3
    - section3.2
    - section3.2.1


- name: "3.2.2 Ensure IP forwarding is disabled (Automated)"
  become: yes
  sysctl:
    name: "{{ item }}"
    value: '0'
    state: present
    reload: true
    sysctl_set: true
    ignoreerrors: true
  with_items:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.forwarding
  when: level1|bool
  tags:
    - section3
    - section3.2
    - section3.2.2
