- name: "2.1.3.1 Ensure systemd-timesyncd configured with authorized timeserver (Manual)"
  become: yes
  block:
    - name: "2.1.3.1 | configure ntp server"
      copy: 
        path: "/etc/systemd/timesyncd.conf"
        content: |
          # /etc/systemd/timesyncd.conf
          {{ hardening_header }}
          [Time]
          NTP={{ ntp_server1 ntp_server2 }}
        owner: root
        group: root
        mode: 0644
  when: level1|bool
  tags:
    - section2
    - section2.1
    - section2.1.3
    - section2.1.3.1

- name: "2.1.3.2 Ensure systemd-timesyncd is enabled and running (Automated)"
  become: yes
  block:
    systemd:
      name: systemd-timesyncd
      state: started
      enabled: yes
    command: "timedatectl set-ntp true"
  when: level1|bool
  tags:
    - section2
    - section2.1
    - section2.1.3
    - section2.1.3.1

