- name: "1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Automated)"
  become: yes
  vars:
      cramfs_config: "/etc/modprobe.d/cramfs.conf"
  block:
    - name: "1.1.1.1 |-> Disabling cramfs"
      modprobe: 
        name: cramfs
        state: absent
    - name: "1.1.1.1 |-> Writing {{ cramfs_config }}"
      copy:
        dest: "{{ cramfs_config }}"
        content: |
             # {{ cramfs_config }}
             #
             # {{ hardening_header }}
             install cramfs /bin/true
             blacklist cramfs
        mode: 0644
        owner: root
        group: root
  when: level1|bool == True
  tags:
    - section1
    - section1.1
    - section1.1.1
    - section1.1.1.1


- name: "1.1.1.2 Ensure mounting of squashfs filesystems is disabled (Automated)"
  become: yes
  vars:
      squashfs_config: "/etc/modprobe.d/squashfs.conf"
  block:
    - name: "1.1.1.2 |-> Disabling squashfs"
      modprobe: 
        name: squashfs
        state: absent
  
    - name: "1.1.1.2 |-> Writing {{ squashfs_config }}"
      copy:
        dest: "{{ squashfs_config }}"
        content: |
             # {{ squashfs_config }}
             #
             # {{ hardening_header }}
             install squashfs /bin/true
             blacklist squashfs
        mode: 0644
        owner: root
        group: root
  when: level2|bool == True
  tags:
    - section1
    - section1.1
    - section1.1.1
    - section1.1.1.2

- name: "1.1.1.3 Ensure mounting of udf filesystems is disabled (Automated"
  become: yes
  vars:
      udf_config: "/etc/modprobe.d/udf.conf"
  block:
    - name: "1.1.1.3 |-> Disabling udf"
      modprobe: 
        name: udf
        state: absent
  
    - name: "1.1.1.3 |-> Writing {{ udf_config }}"
      copy:
        dest: "{{ udf_config }}"
        content: |
             # {{ udf_config }}
             #
             # {{ hardening_header }}
             install udf /bin/true
             blacklist udf
        mode: 0644
        owner: root
        group: root
  when: level2|bool == True
  tags:
    - section1
    - section1.1
    - section1.1.1
    - section1.1.1.3

