- name: "1.6.1.1 Ensure AppArmor is installed (Automated)"
  become: yes
  block:
    - name: "1.6.1.1.1 | install apparmor"
      apt:
        name: ["apparmor", "apparmor-utils", "apparmor-profiles"]
        state: present
        update_cache: yes
      notify: reboot
    - name: "1.6.1.1.3 | enable apparmor daemon"
      systemd:
          name: apparmor
          state: started
          enabled: yes
      notify: reboot
  when: level1|bool

- name: "1.6.1.2 Ensure AppArmor is enabled in the bootloader configuration (Automated)"
  become: yes
  block:
    - name: "1.6.1.2.1 | enable apparmor in GRUB configuration"
      replace: dest="/etc/default/grub" regexp='^GRUB_CMDLINE_LINUX="(((?!apparmor=).)*)"$' replace='GRUB_CMDLINE_LINUX="\1 apparmor=1"'
      when: grub_password_v2_unrestricted|bool
      notify: "update grub"
      notify: "reboot"
    - name: "1.6.1.2.2 | choose apparmor as MAC provider "
      replace: dest="/etc/default/grub" regexp='^GRUB_CMDLINE_LINUX="(((?!security=).)*)"$' replace='GRUB_CMDLINE_LINUX="\1 security=apparmor"'
      notify: "update grub"
      notify: "reboot"
  when: level1|bool

- name: "1.6.1.3 Ensure all AppArmor Profiles are in enforce or complain mode (Automated)"
  become: yes
  block:
    - name: "1.6.1.3.1 | enable complain mode"
      command: /usr/sbin/aa-complain /etc/apparmor.d/*
      when: enable_apparmor_complain == True and level2 == False
      notify: reboot
    - name: "1.6.1.3.2 | enable enforce mode"
      command: /usr/sbin/aa-enforce /etc/apparmor.d/*
      when: enable_apparmor_enforce|bool
      notify: reboot
  when: level1|bool

- name: "1.6.1.4 Ensure all AppArmor Profiles are enforcing (Automated)"
  become: yes
  command: /usr/sbin/aa-enforce /etc/apparmor.d/*
  notify: reboot
  when: level2|bool

