- name: "1.1.1 Disable Unused Filesystems"
  become: yes
  vars:
      cramfs_config: "/etc/modprobe.d/cramfs.conf"
  block:
    - name: "1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Automated) | Disabling cramfs"
      modprobe: 
        name: cramfs
        state: absent
  
    - name: "1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Automated) | Writing {{ cramfs_config }}"
      copy:
        dest: "{{ cramfs_config }}"
        content: |
             install cramfs /bin/true
  
    - name: "1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Automated) | Setting ownership + permissions to {{ cramfs_config }}"
      file: 
        path: "{{ cramfs_config }}"
        mode: 0644
        owner: root
  
  tags:
    - level1
    - level2
    - section1.1



- name: 
